<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Inventory&BillingSystem.aspx.cs" Inherits="Inventory_BillingSystem.Inventory_BillingSystem" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
	<style type="text/css">
		.auto-style1 {
			width: 100%;
		}
		.auto-style2 {
			width: 419px;
		}
		.auto-style3 {
			width: 419px;
			height: 42px;
		}
		.auto-style4 {
			height: 42px;
		}
		.auto-style5 {
			width: 419px;
			height: 16px;
		}
		.auto-style6 {
			height: 16px;
		}
		.auto-style7 {
			width: 419px;
			height: 43px;
		}
		.auto-style8 {
			height: 43px;
		}
	</style>
</head>
<body>
    <form id="form1" runat="server">
		<table class="auto-style1" align="center">
			<tr>
				<td colspan="2">
					<asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="XX-Large" ForeColor="#006699" Text="INVENTORY AND BILLING" BackColor="#CCFFCC"></asp:Label>
				</td>
			</tr>
			<tr>
				<td class="auto-style2">&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td class="auto-style3">
					<asp:Label ID="Label2" runat="server" Font-Bold="True" Font-Size="X-Large" ForeColor="#660066" Text="Item Id : "></asp:Label>
				</td>
				<td class="auto-style4">
					<asp:TextBox ID="txt_id" runat="server" Font-Size="X-Large"></asp:TextBox>
				</td>
			</tr>
			<tr>
				<td class="auto-style3">
					<asp:Label ID="Label3" runat="server" Font-Bold="True" Font-Size="X-Large" ForeColor="#660066" Text="Item Name : "></asp:Label>
				</td>
				<td class="auto-style4">
					<asp:TextBox ID="txt_name" runat="server" Font-Size="X-Large"></asp:TextBox>
				</td>
			</tr>
			<tr>
				<td class="auto-style3">
					<asp:Label ID="Label4" runat="server" Font-Bold="True" Font-Size="X-Large" ForeColor="#660066" Text="Category : "></asp:Label>
				</td>
				<td class="auto-style4">
					<asp:TextBox ID="txt_category" runat="server" Font-Size="X-Large"></asp:TextBox>
				</td>
			</tr>
			<tr>
				<td class="auto-style3">
					<asp:Label ID="Label5" runat="server" Font-Bold="True" Font-Size="X-Large" ForeColor="#660066" Text="Price : "></asp:Label>
				</td>
				<td class="auto-style4">
					<asp:TextBox ID="txt_price" runat="server" Font-Size="X-Large"></asp:TextBox>
				</td>
			</tr>
			<tr>
				<td class="auto-style3">
					<asp:Label ID="Label6" runat="server" Font-Bold="True" Font-Size="X-Large" ForeColor="#660066" Text="Quantity : "></asp:Label>
				</td>
				<td class="auto-style4">
					<asp:TextBox ID="txt_quantity" runat="server" Font-Size="X-Large"></asp:TextBox>
				</td>
			</tr>
			<tr>
				<td class="auto-style5"></td>
				<td class="auto-style6"></td>
			</tr>
			<tr>
				<td class="auto-style7">
					<asp:Button ID="Button1" runat="server" Font-Bold="True" Font-Size="X-Large" OnClick="Button1_Click" Text="SHOW DATA" />
				</td>
				<td class="auto-style8">
					<asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
					</asp:GridView>
				</td>
			</tr>
		</table>
	</form>
</body>
</html>
